backend:
  name: github
  repo: XxzubcovxX/BlogBoticario
  branch: main
  # A URL do seu servidor Vercel (sem barra no final)
  base_url: https://oauthgobblogoboticario.vercel.app/api
  
  # REMOVI O site_domain PARA TESTAR
  # site_domain: ... 

media_folder: "assets/img/produtos"
public_folder: "assets/img/produtos"

# Configurações visuais
display_url: "https://ambitious-desert-072597610.3.azurestaticapps.net"
# site_url removido temporariamente para evitar conflitos de segurança

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Preço Atual", name: "preco", widget: "number", value_type: "float"}
      - {label: "Link da Loja/WhatsApp", name: "link_afiliado", widget: "string"}
      - {label: "Categoria", name: "categoria", widget: "select", options: ["Perfumaria", "Corpo e Banho", "Maquiagem", "Cabelos"]}